game_settings:
  name: Platis
  fps: 60

graphics:
  screen_reduction: 2

background:
  path: ./art/background/
  folder: terrain/
  type: pink.png
  terrain: terrain.png

character: 
  gravity: 1
  velocity: 5
  jump_limit: 2
  jump_velocity: 10
  animation_delay: 3
  path: ./art/characters/ # TODO
  folder: pink_man/