game_settings:
  fps: 60

background:
  path: ./art/background/
  folder: terrain/
  type: pink.png

character: 
  gravity: 1
  velocity: 5
  animation_delay: 3
  path: ./art/characters/ # TODO
  folder: pink_man/